"""empty message

Revision ID: 52036ebadf27
Revises: e105339c5de1
Create Date: 2018-10-21 17:47:40.893529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52036ebadf27'
down_revision = 'e105339c5de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_painting_content_path', table_name='painting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_painting_content_path', 'painting', ['content_path'], unique=False)
    # ### end Alembic commands ###
