"""empty message

Revision ID: 65670c31345c
Revises: 52036ebadf27
Create Date: 2018-10-21 17:49:19.386960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65670c31345c'
down_revision = '52036ebadf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_abstract', table_name='paper')
    op.drop_index('ix_paper_content_path', table_name='paper')
    op.drop_index('ix_photograph_content_path', table_name='photograph')
    op.drop_index('ix_project_abstract', table_name='project')
    op.drop_index('ix_project_content_path', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_content_path', 'project', ['content_path'], unique=False)
    op.create_index('ix_project_abstract', 'project', ['abstract'], unique=False)
    op.create_index('ix_photograph_content_path', 'photograph', ['content_path'], unique=False)
    op.create_index('ix_paper_content_path', 'paper', ['content_path'], unique=False)
    op.create_index('ix_paper_abstract', 'paper', ['abstract'], unique=False)
    # ### end Alembic commands ###
